// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT4SfDLpDGN2uP47na8oP8lTIwzuv1TAE',
    appId: '1:370437669649:web:fb69e178b33f8081c082b0',
    messagingSenderId: '370437669649',
    projectId: 'loja-mochilas',
    authDomain: 'loja-mochilas.firebaseapp.com',
    storageBucket: 'loja-mochilas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAalQZUTNwUNeHxR9Q8VQuoIqX6un3KKJ0',
    appId: '1:370437669649:android:8b779572f8850881c082b0',
    messagingSenderId: '370437669649',
    projectId: 'loja-mochilas',
    storageBucket: 'loja-mochilas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7VMe_subeQWXi-sknp2byrm3l390ay2Y',
    appId: '1:370437669649:ios:d2f1cde51c17960dc082b0',
    messagingSenderId: '370437669649',
    projectId: 'loja-mochilas',
    storageBucket: 'loja-mochilas.appspot.com',
    iosClientId: '370437669649-rkdblfrdt19vlaftj4dvu9g0uqev90qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mochilas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7VMe_subeQWXi-sknp2byrm3l390ay2Y',
    appId: '1:370437669649:ios:d2f1cde51c17960dc082b0',
    messagingSenderId: '370437669649',
    projectId: 'loja-mochilas',
    storageBucket: 'loja-mochilas.appspot.com',
    iosClientId: '370437669649-rkdblfrdt19vlaftj4dvu9g0uqev90qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mochilas',
  );
}
